"""revert test

Revision ID: 5bdcabbc128c
Revises: 07e976913f19
Create Date: 2024-08-15 14:22:09.979112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdcabbc128c'
down_revision = '07e976913f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('crupdated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crupdated_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
